import cn from '@/utils/cn';
import './globals.css';
import type { Metadata } from 'next';
import { Poppins, Rubik } from 'next/font/google';

const poppins = Poppins({
	subsets: ['latin'],
	weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900'],
});

const rubik = Rubik({
	subsets: ['latin'],
	weight: ['300', '400', '500', '600', '700'],
});

export const metadata: Metadata = {
	title: 'SaveUp',
	description: 'Generated by create next app',
	icons: {
		icon: '/images/favicon.png',
		shortcut: '/images/favicon.png',
		apple: '/images/favicon.png',
	},
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
	return (
		<html lang='en'>
			<body className={cn('bg-black text-white h-screen', rubik.className)}>{children}</body>
		</html>
	);
}
